# go releaser yaml file
env:
  - CGO_ENABLED=0
  - PACKER_PROTOCOL_VERSION=x5.0
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  -
    id: plugin-check
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.Version={{.Version}}'
    targets:
      - linux_amd64
  -
    id: default
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.Version={{.Version}}'
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.PACKER_PROTOCOL_VERSION }}_{{ .Os }}_{{ .Arch }}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  -
    builds:
      - default
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.PACKER_PROTOCOL_VERSION }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
